const cat = document.getElementById('cat-container');
const catBody = document.getElementById('cat-body');
const dialogue = document.getElementById('dialogue');
const reaction = document.getElementById('reaction');

// === 500+ ABSURD JOKES ===
const jokes = [
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I'll always remember my grandfather's last words: 'Stop shaking the ladder you little shit!'",
    "My therapist says I have a preoccupation with vengeance. We'll see about that.",
    "I'm reading a book about anti-gravity. It's impossible to put down.",
    "I used to hate facial hair, but then it grew on me.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "I'm on a whiskey diet. I've lost three days already.",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I told my computer I needed a break and now it won't stop sending me Kit Kat ads.",
    "I have a fear of speed bumps, but I'm slowly getting over it.",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    "I used to be addicted to soap, but I'm clean now.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "I'm terrified of elevators, so I'm taking steps to avoid them.",
    "My wife told me to stop impersonating a flamingo. I had to put my foot down.",
    "I accidentally swallowed some food coloring. The doctor says I'm okay, but I feel like I've dyed a little inside.",
    "What do you call a bear with no teeth? A gummy bear.",
    "I couldn't figure out how to put my seatbelt on. Then it clicked.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I asked the librarian if they had any books on paranoia. She whispered, 'They're right behind you.'",
    "I told a chemistry joke. There was no reaction.",
    "I have a joke about construction, but I'm still working on it.",
    "Want to hear a joke about paper? Never mind, it's tearable.",
    "I just watched a documentary on beavers. It was the best dam documentary I've ever seen.",
    "My friend's bakery burned down. Now his business is toast.",
    "I was going to tell a time-traveling joke, but you didn't like it.",
    "I tried to catch fog yesterday. Mist.",
    "Why did the bicycle fall over? It was two tired.",
    "I'm afraid for the calendar. Its days are numbered.",
    "What do you call fake spaghetti? An impasta.",
    "How do you organize a space party? You planet.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "Why did the coffee file a police report? It got mugged.",
    "Don't trust stairs. They're always up to something.",
    "I have a joke about trickle-down economics, but 99% of you will never get it.",
    "I'm friends with 25 letters of the alphabet. I don't know y.",
    "I'm reading a horror story in Braille. Something bad is about to happen, I can feel it.",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "I invented a new word: Plagiarism.",
    "I stayed up all night wondering where the sun went. Then it dawned on me.",
    "Two guys walked into a bar. The third one ducked.",
    "I'm writing a book about hurricanes. It's only a draft right now.",
    "I couldn't believe the highway was congested. I had to take the back road.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'p' is silent.",
    "I used to play piano by ear, but now I use my hands.",
    "I went to buy some camouflage trousers but couldn't find any.",
    "What's orange and sounds like a parrot? A carrot.",
    "I'm skeptical of anyone who tells me they do yoga for the 'mental benefits.' Sure, namaste in bed too.",
    "I have a Russian friend who is a sound engineer. And a Czech one too. Czech one too.",
    "I got fired from the calendar factory. All I did was take a day off.",
    "I started a band called 999 Megabytes. We haven't got a gig yet.",
    "What do you call an alligator in a vest? An investigator.",
    "I hate Russian dolls. They're so full of themselves.",
    "I don't trust people who do acupuncture. They're back stabbers.",
    "I once ate a watch. It was very time consuming.",
    "I'm on a seafood diet. I see food and I eat it.",
    "My wife accused me of being immature. I told her to get out of my fort.",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks.",
    "I wondered why the frisbee kept getting bigger. Then it hit me.",
    "A magician was walking down the street, then turned into a grocery store.",
    "Did you hear about the guy whose left side was cut off? He's all right now.",
    "I broke my finger at work today. On the other hand, I'm completely fine.",
    "The frustrated cannibal threw up his hands.",
    "I finally bought a self-parking car. Turned out it was towed.",
    "Don't spell part backwards. It's a trap.",
    "I ordered a chicken and an egg from Amazon. I'll let you know.",
    "My short-term memory is going. I can't even finish a sent—",
    "I just found out I'm colorblind. The news came right out of the purple.",
    "People say I'm condescending. That means I talk down to people.",
    "I'd tell you a UDP joke, but you might not get it.",
    "There are two types of people in this world: those who can extrapolate from incomplete data.",
    "Archaeologists have the best jobs: they're always moving forward, yet stuck in the past.",
    "I would tell you a joke about infinity, but it has no end.",
    "The rotation of Earth really makes my day.",
    "I had my patience tested yesterday. Turns out I'm negative.",
    "Why did the gym close down? It just didn't work out.",
    "This graveyard is so overcrowded, people are dying to get in.",
    "I went to a seafood disco last week and pulled a mussel.",
    "RIP boiling water. You will be mist.",
    "I got hit in the head with a can of soda. Lucky it was a soft drink.",
    "Why do cows wear bells? Because their horns don't work.",
    "What did one wall say to the other? I'll meet you at the corner.",
    "What does a zombie vegetarian eat? Graaaiiinsss.",
    "I hate how funerals are always at 9 or 10am. I'm not really a mourning person.",
    "I have kleptomania, but when it gets bad, I take something for it.",
    "Claustrophobic people are more productive thinking outside the box.",
    "Why don't oysters donate to charity? Because they're shellfish.",
    "I'm terrified of lifts. I'm going to start taking steps to avoid them.",
    "The shovel was a ground-breaking invention.",
    "A plateau is the highest form of flattery.",
    "Time flies like an arrow. Fruit flies like a banana.",
    "I couldn't work at the orange juice factory. I couldn't concentrate.",
    "I used to be a banker, but I lost interest.",
    "Seven days without a pun makes one weak.",
    "A backwards poet writes inverse.",
    "The man who survived pepper spray and mustard gas is a seasoned veteran.",
    "I'm addicted to brake fluid, but I can stop whenever I want.",
    "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
    "I have a fear of over-engineered buildings. It's a complex complex complex.",
    "The furniture store keeps calling me back. But all I wanted was one night stand.",
    "A boiled egg in the morning is hard to beat.",
    "Velcro – what a rip-off!",
    "War doesn't determine who's right. Only who's left.",
    "Police were called to the day care. A 3-year-old was resisting a rest.",
    "I had a dream I was a muffler. I woke up exhausted.",
    "No matter how much you push the envelope, it'll still be stationery.",
    "I went to the doctor with hearing problems. He said, 'Can you describe the symptoms?' I said, 'Homer's a fat bloke and Marge has blue hair.'",
    "The past, present, and future walked into a bar. It was tense.",
    "I used to be a shoe salesman, but they gave me the boot.",
    "I was struggling to understand how lightning works, then it struck me.",
    "The dead batteries were given out free of charge.",
    "A prisoner's favorite punctuation mark is the period. It marks the end of a sentence.",
    "I once heard a joke about amnesia, but I forgot how it goes.",
    "I don't trust people who do acupuncture. They're back stabbers.",
    "When chemists die, they barium.",
    "I know a guy who is addicted to drinking brake fluid. He says he can stop anytime.",
    "My math teacher called me average. How mean!",
    "I'd tell you a chemistry joke, but I know I wouldn't get a reaction.",
    "The first time I got a universal remote control, I thought to myself, 'This changes everything.'",
    "I didn't like my beard at first. Then it grew on me.",
    "I cut my finger chopping cheese, but I think that I may have grater problems.",
    "A book just fell on my head. I only have my shelf to blame.",
    "What's the difference between ignorance and apathy? I don't know and I don't care.",
    "I got my daughter a fridge for her birthday. I can't wait to see her face light up when she opens it.",
    "Did you hear oxygen went on a date with potassium? It went OK.",
    "Why can't you trust an atom? They make up literally everything.",
    "I wasn't originally going to get a brain transplant, but then I changed my mind.",
    "I got a reversible jacket for Christmas. I can't wait to see how it turns out.",
    "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right.",
    "Who is this Rorschach guy? And why does he paint so many pictures of my parents fighting?",
    "I failed my calculus exam because I was sitting in the middle of identical twins—I couldn't differentiate between them.",
    "I hate when people ask me where I see myself in 4 years. I don't have 2020 vision.",
    "Why did the worker get fired from the orange juice factory? Lack of concentration.",
    "How many surrealists does it take to screw in a light bulb? A fish.",
    "I asked my North Korean friend how it was there. He said, 'Can't complain.'",
    "Why do trees seem suspicious on sunny days? Dunno, they're just a bit shady.",
    "I can't believe I got fired from the calendar factory. All I did was take a day off.",
    "What time did the man go to the dentist? Tooth hurt-y.",
    "I lost my job at the bank on my first day. A woman asked me to check her balance, so I pushed her over.",
    "I gave my seat to a blind person on the bus. That's how I lost my job as a bus driver.",
    "Whiteboards are remarkable.",
    "I got fired from the keyboard factory. I wasn't putting in enough shifts.",
    "Why did the Clydesdale give the pony a glass of water? Because he was a little horse.",
    "What's the tallest building in the world? The library, because it has the most stories.",
    "Geology rocks, but geography is where it's at.",
    "Exaggerations went up by a million percent last year.",
    "I can't take my dog to the pond anymore because the ducks keep attacking him. That's what I get for buying a pure bread dog.",
    "My first job was working in an orange juice factory, but I got canned. Couldn't concentrate.",
    "My pet mouse Elvis died last night. He was caught in a trap.",
    "Someone stole my Microsoft Office and they're gonna pay. You have my Word.",
    "What's the leading cause of dry skin? Towels.",
    "I once worked for a company that sold landmines disguised as prayer mats. Prophets were going through the roof.",
    "I bought a ceiling fan the other day. Complete waste of money. He just stands there applauding and saying 'Ooh, I love how smooth it is.'",
    "I have an inferiority complex, but it's not a very good one.",
    "Communism jokes aren't funny unless everyone gets them.",
    "I didn't think orthopedic shoes would help, but I stand corrected.",
    "I have a phobia of over-engineered buildings. It's a complex complex complex.",
    "Spring is here! I got so excited I wet my plants.",
    "I wasn't going to get a brain transplant, but then I changed my mind.",
    "What's brown and sticky? A stick.",
    "I finally started reading that book about anti-gravity. I can't put it down!",
    "Never trust an atom. They make up everything.",
    "The midget psychic who escaped from prison was a small medium at large.",
    "My granddad has the heart of a lion and a lifetime ban from the zoo.",
    "Rick Astley will let you borrow any of his Pixar movies, except one. He's never gonna give you Up.",
    "I wrote a song about a tortilla. Actually, it's more of a wrap.",
    "Did you hear about the guy who got cooled to absolute zero? He's 0K now.",
    "My girlfriend told me she was leaving me because I keep pretending to be a Transformer. I said, 'No, wait! I can change.'",
    "I have a stepladder. Because my real ladder left when I was just a kid.",
    "I can't believe I got fired from the calendar factory. All I did was take a day off.",
    "For Halloween we dressed up as almonds. Everyone thought we were nuts.",
    "Today a man knocked on my door and asked for a small donation towards the local swimming pool. I gave him a glass of water.",
    "My wife told me to stop acting like a flamingo. So I had to put my foot down.",
    "I'm glad I know sign language. It's pretty handy.",
    "Why did the chicken go to the séance? To talk to the other side.",
    "My wife is mad that I have no sense of direction. So I packed up my stuff and right.",
    "If you see a robbery at an Apple Store, does that make you an iWitness?",
    "I wasn't originally going to get a brain transplant, but then I changed my mind.",
    "I got a new pair of gloves today, but they're both 'lefts,' which on the one hand is great, but on the other, it's just not right.",
    "The first time I got a universal remote control I thought, 'This changes everything.'",
    "What do you call a fake noodle? An impasta.",
    "Why don't scientists trust atoms? They make up everything.",
    "How do you organize an outer space party? You planet.",
    "What happens to a frog's car when it breaks down? It gets toad away.",
    "Justice is a dish best served cold. If it were served warm, it would be justwater.",
    "Why do bees hum? Because they don't know the words.",
    "I saw an ad for burial plots, and thought, 'That's the last thing I need.'",
    "I have an EpiPen. My friend gave it to me when he was dying. It seemed very important to him that I have it.",
    "My wife is really mad that I have no sense of direction. So I packed up my stuff and right.",
    "I'd tell you a Fibonacci joke, but it's probably as bad as the last two you've heard combined.",
    "Someone broke into my house last night and stole my limbo trophy. How low can you go?",
    "I'm friends with almost all the letters of the alphabet. I just don't know y.",
    "When life gives you melons, you might be dyslexic.",
    "I tried to sue the airline for losing my luggage. I lost my case.",
    "The rotation of the Earth really makes my day.",
    "I knew I shouldn't have eaten that seafood. Because now I'm feeling a little... eel.",
    "The other day, my wife asked me to pass her lipstick but I accidentally passed her a glue stick. She still isn't talking to me.",
    "I threw a boomerang a few years ago. I now live in constant fear.",
    "My wife told me I should do lunges to stay in shape. That would be a big step forward.",
    "Why do chicken coops only have two doors? Because if they had four, they'd be chicken sedans.",
    "The fattest knight at King Arthur's round table was Sir Cumference. He acquired his size from too much pi.",
    "Atheism is a non-prophet organization.",
    "What do you call someone with no body and no nose? Nobody knows.",
    "Why can't a bicycle stand on its own? It's two tired.",
    "What do you call a parade of rabbits hopping backwards? A receding hare-line.",
    "I was going to tell a joke about sodium, but Na.",
    "Broken puppets for sale. No strings attached.",
    "Mountains aren't just funny. They're hill areas.",
    "What's E.T. short for? Because he's got little legs.",
    "My friend was showing me his tool shed and pointed to a ladder. 'That's my step ladder,' he said. 'I never knew my real ladder.'",
    "I just found out I'm colorblind. The diagnosis came completely out of the purple.",
    "My wife told me to take the spider out instead of killing it. We went and had drinks. Cool guy. Wants to be a web designer.",
    "The first time I saw a universal remote, I thought, 'Well, this changes everything.'",
    "I wondered why the baseball was getting bigger. Then it hit me.",
    "How did the hipster burn his tongue? He drank his coffee before it was cool.",
    "I haven't slept for three days... because that would be too long.",
    "Why did the Invisible Man turn down the job offer? He couldn't see himself doing it.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Where do you take someone who's been injured in a peek-a-boo accident? To the I.C.U.",
    "How do you get a country girl's attention? A tractor.",
    "I used to think I was indecisive, but now I'm not too sure.",
    "I have a few jokes about unemployed people, but none of them work.",
    "I bought the world's worst thesaurus yesterday. Not only is it terrible, it's terrible.",
    "Ever tried to eat a clock? It's very time consuming.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I was thinking about moving to Moscow but there's no point Russian into things.",
    "Did you hear about the semi-colon that broke the law? He was given two consecutive sentences.",
    "My boss told me to have a good day... so I went home.",
    "What does a baby computer call his father? Data.",
    "A book fell on my head. I've only got my shelf to blame.",
    "Why did the coffee file a police report? It got mugged.",
    "How do you make holy water? You boil the hell out of it.",
    "Don't spell part backwards. It's a trap.",
    "What's the best way to watch a fly fishing tournament? Live stream.",
    "Why was six afraid of seven? Because seven eight nine.",
    "My wife says I only have 2 faults. I don't listen and something else.",
    "People who can't distinguish between etymology and entomology bug me in ways I can't put into words.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What does a house wear? Address.",
    "Why are skeletons so calm? Because nothing gets under their skin.",
    "I like to hold hands at the movies. Which always seems to startle strangers.",
    "My therapist says I have a preoccupation with vengeance. We'll see about that.",
    "Exaggerations went up by a million percent last year.",
    "Have you heard about corduroy pillows? They're making headlines.",
    "I used to hate facial hair, but then it grew on me.",
    "What's Forrest Gump's password? 1forrest1",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks.",
    "A book just fell on my head. I only have my shelf to blame.",
    "I'm reading an anti-gravity book. It's impossible to put down.",
    "Sleeping comes so naturally to me, I could do it with my eyes closed.",
    "What did the left eye say to the right eye? Between us, something smells.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call a fish wearing a crown? King of the sea.",
    "I'm on a whiskey diet. I've lost three days already.",
    "Why do French people eat snails? They don't like fast food.",
    "I'm terrified of elevators, so I'm taking steps to avoid them.",
    "What do you call a pony with a sore throat? A little hoarse.",
    "I'm friends with 25 letters of the alphabet. I don't know y.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "I couldn't figure out why the baseball kept getting larger. Then it hit me.",
    "What do you call a bear with no ears? B.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I'm reading a book on the history of glue. I just can't seem to put it down.",
    "What's orange and sounds like a parrot? A carrot.",
    "A termite walks into a bar and asks, 'Is the bar tender here?'",
    "How do you make a tissue dance? Put a little boogie in it.",
    "I used to play piano by ear. Now I use my hands and fingers.",
    "What's the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle? Attire.",
    "What do you call a group of disorganized cats? A cat-astrophe.",
    "Why couldn't the leopard play hide and seek? Because he was always spotted.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "What did one plate say to the other plate? Dinner's on me.",
    "Why did the stadium get hot after the game? All the fans left.",
    "What do you call a dinosaur that crashes his car? Tyrannosaurus Wrecks.",
    "Why don't skeletons ever go trick or treating? Because they have no body to go with.",
    "I would avoid the sushi if I were you. It's a little fishy.",
    "Want to hear a joke about construction? I'm still working on it.",
    "Did you hear about the claustrophobic astronaut? He just needed a little space.",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "I stayed up all night wondering where the sun went. Then it dawned on me.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Two artists had an art contest. It ended in a draw.",
    "A man got hit in the head with a can of soda. He was lucky it was a soft drink.",
    "What do you call a magical dog? A labracadabrador.",
    "Why was the math book sad? It had too many problems.",
    "I used to be a banker, but I lost interest.",
    "How does a penguin build its house? Igloos it together.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a fake stone in Ireland? A shamrock.",
    "I got carded at a liquor store and my Blockbuster card accidentally fell out. The cashier said never mind.",
    "Why are elevator jokes so classic? They work on many levels.",
    "I tried to catch some fog earlier. I mist.",
    "What concert costs just 45 cents? 50 Cent featuring Nickelback.",
    "Dad, can you put my shoes on? No, I don't think they'll fit me.",
    "What do you call a belt with a watch on it? A waist of time.",
    "Did you hear the rumor about butter? Never mind, I shouldn't spread it.",
    "What did the buffalo say when his son left for college? Bison.",
    "Why couldn't the bicycle stand up by itself? It was two tired.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "I asked my dog what's two minus two. He said nothing.",
    "What do sprinters eat before a race? Nothing, they fast.",
    "Why did the picture go to jail? Because it was framed.",
    "I'm reading a book about anti-gravity. It's impossible to put down.",
    "Why was the belt arrested? For holding up a pair of pants.",
    "What's the best way to carve wood? Whittle by whittle.",
    "Why are ghosts bad liars? Because they are easy to see through.",
    "What's a skeleton's least favorite room? The living room.",
    "I hate jokes about German sausages. They're the wurst.",
    "Why can't you hear a psychologist using the bathroom? Because the P is silent.",
    "What kind of music do planets like? Nep-tunes.",
    "What did the grape do when he got stepped on? He let out a little wine.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "Which state has the most streets? Rhode Island.",
    "I've just written a song about tortillas. Actually, it's more of a wrap.",
    "What do you call a pile of cats? A meow-ntain.",
    "I was wondering why the frisbee kept getting bigger and bigger. Then it hit me.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "What did the pirate say when he turned 80? Aye matey.",
    "Where does the general keep his armies? In his sleevies.",
    "What's brown and sticky? A stick.",
    "Why did the frog take the bus to work? His car got toad away.",
    "How does Moses make his coffee? Hebrews it.",
    "What time is it when the clock strikes 13? Time to get a new clock.",
    "Why shouldn't you write with a broken pencil? Because it's pointless.",
    "I used to run a dating service for chickens, but I was struggling to make hens meet.",
    "Did you know the first French fries weren't actually cooked in France? They were cooked in Greece.",
    "What did the zero say to the eight? Nice belt!",
    "Why are frogs so happy? They eat whatever bugs them.",
    "I don't trust stairs. They're always up to something.",
    "Rest in peace, boiled water. You will be mist.",
    "Why did the nurse need a red pen? In case she needed to draw blood.",
    "What do you call an alligator in a vest? An investigator.",
    "I couldn't remember how to throw a boomerang, but it came back to me.",
    "I was addicted to the hokey pokey, but I turned myself around.",
    "What did the fish say when he swam into a wall? Dam.",
    "A guy walked into a bar. He was disqualified from the limbo contest.",
    "I once got fired from a canned juice company. Apparently, I couldn't concentrate.",
    "Why did the man fall down the well? Because he couldn't see that well.",
    "What happens when you go to the bathroom in France? European.",
    "Why are pirates called pirates? Because they arrrrr.",
    "What did the full glass say to the empty glass? You look drunk.",
    "My friend says to me: 'What rhymes with orange?' I said: 'No it doesn't.'",
    "I'm terrified of lifts. I'm going to start taking steps to avoid them.",
    "Did you hear about the guy who invented Lifesavers? He made a mint.",
    "A man tells his doctor, 'Doc, help me. I'm addicted to Twitter!' The doctor replies, 'Sorry, I don't follow you.'",
    "What kind of shorts do clouds wear? Thunderpants.",
    "Why don't calculus majors throw house parties? Because you should never drink and derive.",
    "Did you hear about the kidnapping at school? It's okay, he woke up.",
    "I used to be addicted to soap, but I'm clean now.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What's the difference between a hippo and a zippo? One is really heavy and the other is a little lighter.",
    "My wife asked me to sync her phone. So I threw it into the ocean.",
    "Why did the computer go to the doctor? Because it had a virus.",
    "I got fired from my job at the bank today. An old lady asked me to check her balance, so I pushed her over.",
    "How do you organize a space party? You planet.",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    "I have a joke about time travel, but you didn't like it.",
    "What's Forrest Gump's email password? 1forrest1",
    "Why don't scientists trust atoms? Because they make up everything.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why did the coffee file a police report? It got mugged.",
    "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
    "I ordered a chicken and an egg from Amazon. I'll let you know which comes first.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call a fake noodle? An impasta.",
    "I'm on a seafood diet. Every time I see food, I eat it.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call a bear with no teeth? A gummy bear.",
    "I'm reading a book on anti-gravity. It's impossible to put down.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What's orange and sounds like a parrot? A carrot.",
    "Why did the scarecrow become a successful motivational speaker? Because he was outstanding in his field.",
    "I couldn't figure out how to put my seatbelt on. Then it clicked.",
    "What do you call a pile of cats? A meow-ntain.",
    "Why are elevator jokes so good? They work on many levels.",
    "Did you hear about the Italian chef who died? He pasta way.",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I used to hate facial hair, but then it grew on me.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I'm terrified of elevators, so I'm taking steps to avoid them.",
    "What's the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle? Attire.",
    "Why can't you hear a pterodactyl using the bathroom? Because the 'p' is silent.",
    "I stayed up all night wondering where the sun went. Then it dawned on me.",
    "What do you call a dog magician? A labracadabrador.",
    "Why did the stadium get hot after the game? All the fans left."
];

// === STATE MANAGEMENT ===
let state = 'IDLE';
let idleTimer = 0;

// === LIFELIKE IDLE BEHAVIORS ===
const idleBehaviors = ['LOAF', 'SPLOOT', 'BLINK', 'TWITCH'];

function setState(newState) {
    console.log('State:', newState);
    state = newState;

    cat.classList.remove('loaf', 'sploot', 'roach', 'startle', 'zoomies', 'elevator-butt');
    reaction.innerText = '';
    catBody.style.transform = '';

    if (newState === 'LOAF') cat.classList.add('loaf');
    else if (newState === 'SPLOOT') cat.classList.add('sploot');
    else if (newState === 'ROACH') cat.classList.add('roach');
    else if (newState === 'STARTLE') cat.classList.add('startle');
    else if (newState === 'ELEVATOR') cat.classList.add('elevator-butt');
}

// Idle animation loop
setInterval(() => {
    if (state !== 'IDLE') return;

    const r = Math.random();
    if (r < 0.3) {
        setState('LOAF');
        setTimeout(() => setState('IDLE'), 4000);
    } else if (r < 0.5) {
        setState('SPLOOT');
        setTimeout(() => setState('IDLE'), 3000);
    }
}, 8000);

// === BUTTON INTERACTIONS ===
const praises = [
    "🥰 You're amazing!",
    "😊 I appreciate you!",
    "✨ You're doing great!",
    "💖 Best human ever!"
];

const quotes = [
    "The only true wisdom is knowing you know nothing. - Socrates",
    "I think, therefore I am. - René Descartes",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "The unexamined life is not worth living. - Socrates",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Get busy living or get busy dying. - Stephen King",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas Edison",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Whoever is happy will make others happy too. - Anne Frank",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "You will face many defeats in life, but never let yourself be defeated. - Maya Angelou",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
    "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "Not all those who wander are lost. - J.R.R. Tolkien",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "If you look at what you have in life, you'll always have more. - Oprah Winfrey",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "Life is made of ever so many partings welded together. - Charles Dickens",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Try not to become a man of success. Rather become a man of value. - Albert Einstein",
    "It is never too late to be what you might have been. - George Eliot",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "Whether you think you can or you think you can't, you're right. - Henry Ford",
    "I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks",
    "I alone cannot change the world, but I can cast a stone across the water to create many ripples. - Mother Teresa",
    "Nothing is impossible, the word itself says I'm possible! - Audrey Hepburn",
    "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "We may encounter many defeats but we must not be defeated. - Maya Angelou",
    "Security is mostly a superstition. Life is either a daring adventure or nothing. - Helen Keller",
    "The mind is everything. What you think you become. - Buddha",
    "The best revenge is massive success. - Frank Sinatra",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
    "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it. - Johann Wolfgang von Goethe",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown Jr.",
    "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
    "Inspiration does exist, but it must find you working. - Pablo Picasso",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "Happiness is not by chance, but by choice. - Jim Rohn",
    "Impossible is a word to be found only in the dictionary of fools. - Napoleon Bonaparte",
    "No matter what you're going through, there's a light at the end of the tunnel. - Demi Lovato",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "You do not find the happy life. You make it. - Camilla Eyring Kimball",
    "If opportunity doesn't knock, build a door. - Milton Berle",
    "Don't limit yourself. Many people limit themselves to what they think they can do. - Mary Kay Ash",
    "The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart",
    "How wonderful it is that nobody need wait a single moment before starting to improve the world. - Anne Frank",
    "An unexamined life is not worth living. - Socrates",
    "Everything you can imagine is real. - Pablo Picasso",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "It is our choices that show what we truly are, far more than our abilities. - J.K. Rowling",
    "The only thing standing between you and your goal is the story you keep telling yourself. - Jordan Belfort",
    "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Life is 10% what happens to you and 90% how you react to it. - Charles R. Swindoll",
    "What we think, we become. - Buddha",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "When everything seems to be going against you, remember that the airplane takes off against the wind. - Henry Ford",
    "Too many of us are not living our dreams because we are living our fears. - Les Brown",
    "I didn't fail the test. I just found 100 ways to do it wrong. - Benjamin Franklin",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "The person who says it cannot be done should not interrupt the person who is doing it. - Chinese Proverb",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
    "Every child is an artist. The problem is how to remain an artist once he grows up. - Pablo Picasso",
    "You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus",
    "Either you run the day or the day runs you. - Jim Rohn",
    "Knowing is not enough; we must apply. Willing is not enough; we must do. - Johann Wolfgang von Goethe",
    "Imagine your life is perfect in every respect; what would it look like? - Brian Tracy",
    "We generate fears while we sit. We overcome them by action. - Dr. Henry Link",
    "Whether you think you can or think you can't, you're right. - Henry Ford",
    "What you lack in talent can be made up with desire, hustle and giving 110% all the time. - Don Zimmer",
    "Do what you feel in your heart to be right, for you'll be criticized anyway. - Eleanor Roosevelt",
    "Happiness is not something you postpone for the future; it is something you design for the present. - Jim Rohn",
    "The way I see it, if you want the rainbow, you gotta put up with the rain. - Dolly Parton",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
    "If you're offered a seat on a rocket ship, don't ask what seat! Just get on. - Sheryl Sandberg",
    "I'd rather regret the things I've done than regret the things I haven't done. - Lucille Ball",
    "A person's success in life can usually be measured by the number of uncomfortable conversations he or she is willing to have. - Tim Ferriss",
    "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better. - Jim Rohn",
    "No one is to blame for your future situation but yourself. - Robert Kiyosaki",
    "You must expect great things of yourself before you can do them. - Michael Jordan",
    "The only thing worse than starting something and failing is not starting something. - Seth Godin",
    "If you genuinely want something, don't wait for it – teach yourself to be impatient. - Gurbaksh Chahal",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
    "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
    "Build your own dreams, or someone else will hire you to build theirs. - Farrah Gray",
    "The battles that count aren't the ones for gold medals. The struggles within yourself are the toughest. - Jesse Owens",
    "Courage is resistance to fear, mastery of fear – not absence of fear. - Mark Twain",
    "Only put off until tomorrow what you are willing to die having left undone. - Pablo Picasso",
    "We become what we think about most of the time. - Earl Nightingale",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Too many people overvalue what they are not and undervalue what they are. - Malcolm S. Forbes",
    "If you want to achieve excellence, you can get there today. Stop doing less-than-excellent work. - Thomas J. Watson",
    "All progress takes place outside the comfort zone. - Michael John Bobak",
    "If everything was perfect, you would never learn and you would never grow. - Beyoncé",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Someday is not a day of the week. - Denise Brennan-Nelson",
    "The distance between insanity and genius is measured only by success. - Bruce Feirstein",
    "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
    "A man who dares to waste one hour of time has not discovered the value of life. - Charles Darwin",
    "If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
    "We can easily forgive a child who is afraid of the dark; the real tragedy is when men are afraid of the light. - Plato",
    "Teach thy tongue to say, 'I do not know,' and thous shalt progress. - Maimonides",
    "The cure for boredom is curiosity. There is no cure for curiosity. - Dorothy Parker",
    "An investment in knowledge pays the best interest. - Benjamin Franklin",
    "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
    "Anyone who stops learning is old, whether at twenty or eighty. - Henry Ford",
    "Wisdom is not a product of schooling but of the lifelong attempt to acquire it. - Albert Einstein",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "The beautiful thing about learning is that nobody can take it away from you. - B.B. King",
    "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. - Brian Herbert",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "A wise man can learn more from a foolish question than a fool can learn from a wise answer. - Bruce Lee",
    "Learning never exhausts the mind. - Leonardo da Vinci",
    "For the things we have to learn before we can do them, we learn by doing them. - Aristotle",
    "Intelligence is the ability to adapt to change. - Stephen Hawking",
    "In learning you will teach, and in teaching you will learn. - Phil Collins",
    "The expert in anything was once a beginner. - Helen Hayes",
    "I am still learning. - Michelangelo",
    "Develop a passion for learning. If you do, you will never cease to grow. - Anthony J. D'Angelo",
    "The more I live, the more I learn. The more I learn, the more I realize, the less I know. - Michel Legrand",
    "Change is the end result of all true learning. - Leo Buscaglia",
    "Study without desire spoils the memory, and it retains nothing that it takes in. - Leonardo da Vinci",
    "Knowledge will bring you the opportunity to make a difference. - Claire Fagin",
    "The secret of getting ahead is getting started. - Mark Twain",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "The best way to predict the future is to create it. - Peter Drucker",
    "You define your own life. Don't let other people write your script. - Oprah Winfrey",
    "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
    "Spread love everywhere you go. - Mother Teresa",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. - Martin Luther King Jr.",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "Well done is better than well said. - Benjamin Franklin",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. - Bil Keane",
    "The positive thinker sees the invisible, feels the intangible, and achieves the impossible. - Winston Churchill",
    "Don't cry because it's over, smile because it happened. - Dr. Seuss",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Life isn't about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "May you live every day of your life. - Jonathan Swift",
    "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. - Albert Einstein",
    "Each person must live their life as a model for others. - Rosa Parks",
    "Love the life you live. Live the life you love. - Bob Marley",
    "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany",
    "Fall seven times and stand up eight. - Japanese Proverb",
    "Everything has beauty, but not everyone can see it. - Confucius",
    "It is only in the mysterious equations of love that any logic or reasons can be found. - John Nash",
    "Love all, trust a few, do wrong to none. - William Shakespeare",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom. - Isaac Asimov",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
    "The best way out is always through. - Robert Frost",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
    "Life is a succession of lessons which must be lived to be understood. - Ralph Waldo Emerson",
    "Your life does not get better by chance, it gets better by change. - Jim Rohn",
    "Life is trying things to see if they work. - Ray Bradbury",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas Edison",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "Life is a long lesson in humility. - James M. Barrie",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "Love yourself first and everything else falls into line. - Lucille Ball",
    "I've failed over and over and over again in my life and that is why I succeed. - Michael Jordan",
    "Accept who you are. Unless you're a serial killer. - Ellen DeGeneres",
    "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
    "Money and success don't change people; they merely amplify what is already there. - Will Smith",
    "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou",
    "Life is 10% what happens to me and 90% of how I react to it. - Charles Swindoll",
    "The most common way people give up their power is by thinking they don't have any. - Alice Walker",
    "The mind is not a vessel to be filled, but a fire to be kindled. - Plutarch",
    "The greatest wealth is to live content with little. - Plato",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "Fortune favors the brave. - Virgil",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "We must balance conspicuous consumption with conscious capitalism. - Kevin Kruse",
    "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine. - Roy T. Bennett",
    "I learned that courage was not the absence of fear, but the triumph over it. - Nelson Mandela",
    "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. - Aristotle",
    "Do what you love and the money will follow. - Marsha Sinetar",
    "We must be willing to let go of the life we planned so as to have the life that is waiting for us. - Joseph Campbell",
    "A successful person is one who can lay a firm foundation with the bricks that others throw at them. - David Brinkley",
    "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
    "A journey of a thousand miles must begin with a single step. - Lao Tzu",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. - Winston Churchill",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
    "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you. - Steve Jobs",
    "People who are crazy enough to think they can change the world, are the ones who do. - Rob Siltanen",
    "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
    "We know what we are, but know not what we may be. - William Shakespeare",
    "To handle yourself, use your head; to handle others, use your heart. - Eleanor Roosevelt",
    "The emotion that can break your heart is sometimes the very one that heals it. - Nicholas Sparks",
    "Perfection is not attainable, but if we chase perfection we can catch excellence. - Vince Lombardi",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. - Maya Angelou",
    "Happiness is not by chance, but by choice. - Jim Rohn",
    "If something is important enough, even if the odds are stacked against you, you should still do it. - Elon Musk",
    "Hold the vision, trust the process. - Unknown",
    "Life is like a camera. Focus on what's important, capture the good times, develop from the negatives. - Unknown",
    "The greatest discovery of all time is that a person can change their future by merely changing their attitude. - Oprah Winfrey",
    "Whether you think you can or think you can't, you're right. - Henry Ford",
    "Life is about making an impact, not making an income. - Kevin Kruse",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Don't be distracted by criticism. Remember--the only taste of success some people get is to take a bite out of you. - Zig Ziglar",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Stop chasing the money and start chasing the passion. - Tony Hsieh",
    "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
    "I never dreamed about success, I worked for it. - Estée Lauder",
    "Success seems to be connected with action. Successful people keep moving. - Conrad Hilton",
    "Without hard work, nothing grows but weeds. - Gordon B. Hinckley",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "In order to succeed, we must first believe that we can. - Nikos Kazantzakis",
    "Success isn't always about greatness. It's about consistency. - Dwayne Johnson",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure. - Colin Powell",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending. - Carl Bard",
    "I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite. - G.K. Chesterton",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference. - Robert Frost",
    "Believe and act as if it were impossible to fail. - Charles Kettering",
    "A real entrepreneur is somebody who has no safety net underneath them. - Henry Kravis",
    "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. - Mark Caine",
    "The only person you should try to be better than is the person you were yesterday. - Anonymous",
    "The function of leadership is to produce more leaders, not more followers. - Ralph Nader",
    "Out of clutter, find simplicity. - Albert Einstein",
    "The difference between winning and losing is most often not quitting. - Walt Disney",
    "Setting goals is the first step in turning the invisible into the visible. - Tony Robbins",
    "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "Your positive action combined with positive thinking results in success. - Shiv Khera",
    "If you don't value your time, neither will others. Stop giving away your time and talents. - Kim Garst",
    "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened. - Helen Keller",
    "Quality is not an act, it is a habit. - Aristotle",
    "Discipline is the bridge between goals and accomplishment. - Jim Rohn",
    "Knowing yourself is the beginning of all wisdom. - Aristotle",
    "Sometimes you win, sometimes you learn. - John Maxwell",
    "Innovation distinguishes between a leader and a follower. - Steve Jobs",
    "Whatever the mind of man can conceive and believe, it can achieve. - Napoleon Hill",
    "The function of education is to teach one to think intensively and to think critically. - Martin Luther King, Jr.",
    "The measure of intelligence is the ability to change. - Albert Einstein",
    "Logic will get you from A to B. Imagination will take you everywhere. - Albert Einstein",
    "The true sign of intelligence is not knowledge but imagination. - Albert Einstein",
    "Intelligence without ambition is a bird without wings. - Salvador Dali",
    "A good head and a good heart are always a formidable combination. - Nelson Mandela",
    "Small minds discuss persons. Average minds discuss events. Great minds discuss ideas. Really great minds discuss ice cream. - Unknown",
    "I am always doing that which I cannot do, in order that I may learn how to do it. - Pablo Picasso",
    "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus. - Alexander Graham Bell",
    "Either you run the day or the day runs you. - Jim Rohn",
    "Optimism is the faith that leads to achievement. - Helen Keller",
    "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
    "It's not the load that breaks you down, it's the way you carry it. - Lou Holtz",
    "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "Our greatest weakness lies in giving up. - Thomas Edison",
    "A goal is a dream with a deadline. - Napoleon Hill",
    "Fall down seven times, get up eight. - Japanese Proverb",
    "A year from now you may wish you had started today. - Karen Lamb",
    "Set your goals high, and don't stop till you get there. - Bo Jackson",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Do not be embarrassed by your failures, learn from them and start again. - Richard Branson",
    "It's fine to celebrate success, but it is more important to heed the lessons of failure. - Bill Gates",
    "If you're going through hell, keep going. - Winston Churchill",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron",
    "The critical ingredient is getting off your butt and doing something. - Nolan Bushnell",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "Doubt kills more dreams than failure ever will. - Suzy Kassem",
    "Be kind whenever possible. It is always possible. - Dalai Lama",
    "What we achieve inwardly will change outer reality. - Plutarch",
    "You can't fall if you don't climb. But there's no joy in living your whole life on the ground. - Unknown",
    "The only way of discovering the limits of the possible is to venture a little way past them into the impossible. - Arthur C. Clarke",
    "Doubt is a killer. You just have to know who you are and what you stand for. - Jennifer Lopez",
    "The hard days are what make you stronger. - Aly Raisman",
    "Don't let what you cannot do interfere with what you can do. - John Wooden",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Try not. Do, or do not. There is no try. - Yoda",
    "Don't count the days, make the days count. - Muhammad Ali",
    "Life begins at the end of your comfort zone. - Neale Donald Walsch",
    "Act as if what you do makes a difference. It does. - William James",
    "To be a champion, I think you have to see the big picture. It's not about winning and losing; it's about every day hard work. - Summer Sanders",
    "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
    "Strength does not come from winning. Your struggles develop your strengths. - Arnold Schwarzenegger",
    "Don't dream about success. Get out there and work for it. - Unknown",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "Dream bigger. Do bigger. - Unknown",
    "Great things never come from comfort zones. - Unknown",
    "Success doesn't just find you. You have to go out and get it. - Unknown",
    "The key to success is to focus on goals, not obstacles. - Unknown",
    "Dream it. Wish it. Do it. - Unknown",
    "Success is what comes after you stop making excuses. - Luis Galarza",
    "Don't stop until you're proud. - Unknown",
    "Work hard in silence. Let success make the noise. - Unknown",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "You are capable of more than you know. - Glinda the Good Witch",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Don't be pushed by your problems. Be led by your dreams. - Ralph Waldo Emerson",
    "What you do today can improve all your tomorrows. - Ralph Marston",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths. - Unknown",
    "The secret to getting ahead is getting started. - Mark Twain",
    "Always do your best. What you plant now, you will harvest later. - Og Mandino",
    "Don't wait for opportunity. Create it. - George Bernard Shaw",
    "Some people want it to happen, some wish it would happen, others make it happen. - Michael Jordan",
    "The difference between ordinary and extraordinary is that little extra. - Jimmy Johnson",
    "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford",
    "Don't be afraid to fail. Be afraid not to try. - Michael Jordan",
    "Great things are done by a series of small things brought together. - Vincent Van Gogh",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. - Chantal Sutherland",
    "No matter how you feel, get up, dress up, show up, and never give up. - Regina Brett",
    "When someone tells you it can't be done, it's more a reflection of their limitations, not yours. - Unknown",
    "Motivation comes from working on things we care about. - Sheryl Sandberg",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "You don't have to be perfect to be amazing. - Unknown",
    "Don't be afraid of the space between your dreams and reality. - Belva Davis",
    "Your limitation—it's only your imagination. - Unknown",
    "Push yourself, because no one else is going to do it for you. - Unknown",
    "Sometimes later becomes never. Do it now. - Unknown",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh"
];

document.getElementById('btn-laugh').onclick = () => {
    const randomJoke = jokes[Math.floor(Math.random() * jokes.length)];
    dialogue.innerText = randomJoke;
    reaction.innerText = '😂';
    setTimeout(() => {
        reaction.innerText = '';
    }, 4000);
};

document.getElementById('btn-praise').onclick = () => {
    dialogue.innerText = praises[Math.floor(Math.random() * praises.length)];
    setState('ELEVATOR');
    reaction.innerText = '😊';
    setTimeout(() => {
        setState('IDLE');
        reaction.innerText = '';
    }, 3000);
};

document.getElementById('btn-quote').onclick = () => {
    dialogue.innerText = quotes[Math.floor(Math.random() * quotes.length)];
    setState('LOAF');
    reaction.innerText = '🧠';
    setTimeout(() => {
        setState('IDLE');
        reaction.innerText = '';
    }, 4000);
};

document.getElementById('btn-surprise').onclick = () => {
    setState('STARTLE');
    dialogue.innerText = "😱 WHAT WAS THAT?!";
    reaction.innerText = '😱';
    setTimeout(() => {
        // Random surprise outcome
        const surprises = ['SPLOOT', 'ROACH', 'LOAF'];
        const randomState = surprises[Math.floor(Math.random() * surprises.length)];
        setState(randomState);
        dialogue.innerText = "Okay, false alarm...";
        setTimeout(() => setState('IDLE'), 3000);
    }, 800);
};

// Initialize
setState('IDLE');
